### ISSUE TITLE
repeated link

### ISSUE THREAD

**Issue by miguelgfierro** [bharathgs/Awesome-pytorch-list#12]
ey, you have tensorboard repeated twice:
19. tensorboard-pytorch: This module saves PyTorch tensors in tensorboard format for inspection. Currently supports scalar, image, audio, histogram features in tensorboard.
24. tensorboard-pytorch: tensorboard for pytorch

**Comment by bharathgs** [comment]
@miguelgfierro  thanks for pointing that out.
