### ISSUE TITLE
Ask about End-to-end audiovisual speech recognition to generate .npy code

### ISSUE THREAD

**Issue by wanli4717** [bharathgs/Awesome-pytorch-list#59]
I'm sorry to disturb you on this. My email to you was returned. I can only communicate with you through GitHub platform. Now I am reproducing the experimental results in End-to-end audiovisual speech recognition, but because of my .npy generation process problems, resulting in poor performance of the experimental results, I saw you reproduce the experimental results on github, I want you to send me a .npy generation code. (wanli@tju.edu.cn)

**Comment by Annastaciahubbard** [comment]
What email are you using for me?
