### ISSUE TITLE
list repos based on date

### ISSUE THREAD

**Issue by vainaijr** [bharathgs/Awesome-pytorch-list#72]
just a suggestion, list would be better if date is also available, that is date last modified of the repositories.
is it possible to do this, and automate it, that is date last modified gets updated as a repo is updated.

**Comment by bharathgs** [comment]
@vainaijr am not really sure if I could do that, but If you have an idea as to how we could do this, it would be a nice addition. let me know how we could proceed with it, even better if you could add a PR, which would be really useful.
