### ISSUE TITLE
Can I create a Chinese version of this list based on your collection?

### ISSUE THREAD

**Issue by xavier-zy** [bharathgs/Awesome-pytorch-list#76]

**Comment by bharathgs** [comment]
@xavier-zy hey, that's a great idea please go ahead.(the only requirement is please add the link/credits to this in the Chinese version.)

**Comment by xavier-zy** [comment]
@bharathgs Thanks a lot.

**Comment by xavier-zy** [comment]
@bharathgs [Awesome-pytorch-list-CNVersion](https://github.com/xavier-zy/Awesome-pytorch-list-CNVersion) is the Chinese version of "Awesome-pytorch-list". Lots of translation work to be done. Hope you like it. BTW, I added star number of each repo using Github API.

**Comment by bharathgs** [comment]
hey, @xavier-zy I just noticed that you might have exposed your GitHub credentials in your notebook that you have. I would suggest removing it.

and addition of star count looks good :+1:

**Comment by xavier-zy** [comment]
@bharathgs  Awkward~~~ forgot to remove. Thanks for reminding
